name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Isso irá rodar a ação todos os dias à meia-noite
  push:
    branches:
      - main  # Executa sempre que houver um push na branch principal (main)

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=#00FF00&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      - name: Commit and push generated files
        uses: EndBug/add-and-commit@v7
        with:
          add: 'dist/*'
          message: 'Update GitHub Snake with green snake'
